CREATE DATABASE donum;
CREATE DATABASE banstick;
CREATE DATABASE bastion;
CREATE DATABASE citadel;
CREATE DATABASE civchat2;
CREATE DATABASE civduties;
CREATE DATABASE jukealert;
CREATE DATABASE namelayer;
CREATE DATABASE civmodcore;
CREATE DATABASE castlegates;
CREATE DATABASE essenceglue;
CREATE DATABASE exilepearl;
CREATE DATABASE realisticbiomes;

GRANT ALL PRIVILEGES ON `donum`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `banstick`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `bastion`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `citadel`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `civchat2`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `civduties`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `jukealert`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `namelayer`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `civmodcore`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `castlegates`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `essenceglue`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `exilepearl`.* TO 'mariadb'@'%';
GRANT ALL PRIVILEGES ON `realisticbiomes`.* TO 'mariadb'@'%';
